# Generated by Django 5.0.3 on 2024-03-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consumers', to='shop.shopuser'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_consumers', to='shop.shopuser'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_created', to='shop.shopuser'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_updated', to='shop.shopuser'),
        ),
    ]
